- name: nginx
  hosts: all
  become: true
  tasks:
    - name: update apt cache
      tags: update_apt
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes


    - name: install nginx
      tags: install_nginx,always
      apt: name=nginx state=latest


    - name: start nginx
      service:
        name: nginx
        state: started
        use: service

#    - name: Copy file with owner and permissions
#      ansible.builtin.copy:
#        src: ./index.html
#        dest: /var/www/html
#    - name: Restart nginx
#      ansible.builtin.service:
#         name: nginx
#         state: restarted
#         use: service
