- name: nginx
  hosts: all
  become: true
#  vars:
#    package_name: nginx
#    package_version: latest
  tasks:
    - name: update apt cache
      tags: update_apt
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: install packages
      apt:
        name: "{{ item.package_name }}"
        state: "{{ item.package_state }}"
      loop:
        - { package_name: "nginx", package_state: "present" }
        - { package_name: "mariadb-server", package_state: "latest" }
        - { package_name: "curl", package_state: "absent" }


    - name: install {{ package_name }}
      tags: install_nginx,always
      apt: name={{ package_name }} state={{ package_version }}


    - name: start nginx
      service:
        name: nginx
        state: started
        use: service

#    - name: Copy file with owner and permissions
#      ansible.builtin.copy:
#        src: ./index.html
#        dest: /var/www/html
#    - name: Restart nginx
#      ansible.builtin.service:
#         name: nginx
#         state: restarted
#         use: service
